apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-database
spec:
  serviceName: {{ .Release.Name }}-database
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      # Рассаживаем реплики по разным нодам для отказоустойчивости
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - database
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          resources:
            requests:
              cpu: {{ .Values.database.resources.requests.cpu }}
              memory: {{ .Values.database.resources.requests.memory }}
            limits:
              cpu: {{ .Values.database.resources.limits.cpu }}
              memory: {{ .Values.database.resources.limits.memory }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.database.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.database.storage.size }}

